name: Lighthouse
permissions:
  contents: read

on: [pull_request]

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Use Node.js 24.x (LTS)
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.x
          cache: 'npm'
      - run: npm ci

      - name: Use Ruby 2.7.3
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: '2.7.3'
          bundler-cache: true
          working-directory: docs

      - name: Build docs
        run: npm run build:docs
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Lighthouse CI
        run: npx @lhci/cli@0.9.x autorun
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LHCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
