name: Publish

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write # for provenance and publish access

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Use Node.js 24.x (LTS)
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/
          cache: npm
      - run: npm ci
      - run: npm test
      - run: npm version ${TAG_NAME} --git-tag-version=false
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
      - run: npm publish --provenance
